version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Counter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ng32pjkf7vv"
s3_prefix = "Counter"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
